name: custom_clocks_app
description: "Custom clocks Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.3
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.3
  get: ^4.6.5
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_switch: ^0.3.2
  country_code_picker: ^3.0.0
  intl_phone_number_input: ^0.7.3+1
  country_state_picker: ^0.0.4
  csc_picker: ^0.2.7
  animations: ^2.0.7
  http: ^0.13.6
  logger: ^1.3.0
  intl: ^0.18.1
  modal_bottom_sheet: ^3.0.0-pre
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  graphql_flutter: ^5.0.0
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  swipeable_button_view: ^0.0.2
  flutter_swiper_view: ^1.1.8
  country_state_city: ^0.1.6
  flutter_csc_picker: ^0.0.2
  country_picker: ^2.0.21
  flutter_widget_from_html: ^0.14.3
  lottie: ^2.7.0
  syncfusion_flutter_datepicker: ^23.1.43
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_animate: ^4.2.0+1
  mercadopago_sdk: ^1.3.0
  flutter_statusbarcolor_ns: ^0.5.0
  provider: ^6.1.1
  rflutter_alert: ^2.0.7
  back_button_interceptor: ^7.0.0
  flutter_paypal_checkout: ^1.0.1
  back_pressed: ^0.0.2
  url_launcher: ^6.2.2
  flutter_paypal_payment: ^1.0.6
  device_preview: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


